### ISSUE TITLE
templates not copied to subfolder

### ISSUE THREAD

**Issue by davidsayers** [berkshelf/berkshelf#1243]
Hi,

When i upload a cookbook that contains subfolders in the templates directory it places all the files in the root folder:

Before Upload:

``` text
templates/
-> default
---> dir1
------> test
---> dir2
------> test
```

On Chef server:

``` text
templates/
-> default
---> test
---> test
```

When I use knife it uploads the files to the correct location.

$ berks -v
3.1.2

$ knife -v
Chef: 11.12.2

Thanks

**Comment by acfreitas** [comment]
@sethvargo, I'm using

**Comment by acfreitas** [comment]
@sethvargo, I'm using [postgresql](https://github.com/hw-cookbooks/postgresql) with Vagrant and Chef-Solo. When I run `berks install` the cookbook postgresl is installed with version (e.g. postgresql-3.4.18) and Chef not found the files and tempaltes because found in `postgresql` and not in ` postgresql-3.4.18`. 
`File templates/default/postgresql.conf.erb does not exist for cookbook postgresql`

**Comment by davidsayers** [comment]
@sethvargo this is still an issue with 3.2.4. I see the problem with the Nginx cookbook https://github.com/miketheman/nginx

nginx/templates/default/modules/ gets copied to nginx/templates/ on the chef server after running "berks upload".

**Comment by davidsayers** [comment]
This is actually a problem with the Ridley gem and not Berkshelf. I see the same behaviour when running the following manually. 

https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/uploader.rb#L55-L60

**Comment by lamont-granquist** [comment]
closing this as berkshelf no longer depends on ridley, if this is still a bug in berkshelf > 7.0 please open a new issue.
