### ISSUE TITLE
Berks update with '--include-deps'

### ISSUE THREAD

**Issue by jmauro** [berkshelf/berkshelf#1265]
Hey,

Adding a flag to berks update such as --include-deps would be great for updating cookbook recursive dependencies.

Regards,
JM

**Comment by FlorentFlament** [comment]
Hi, As far as I understand this issue, ``berks update`` recursively updates the dependencies because of this:
https://github.com/berkshelf/berkshelf/blob/v3.3.0/lib/berkshelf/lockfile.rb#L725

This is the default behavior since commit: https://github.com/berkshelf/berkshelf/commit/c8cdc4f81aa7ef4279f9c5d6c157d508da4c3a05

**Comment by lamont-granquist** [comment]
sounds like this has been fixed since v3.3.0, open a new issue if that's incorrect.

**Comment by thommay** [comment]
Closing since this should have been fixed in 3.0. Thanks for the report!
