### ISSUE TITLE
berkshelf / lib / berkshelf / locations / git.rb : 62 [The issues with unstaged changes on case insensitive file system)

### ISSUE THREAD

**Issue by dee-kryvenko** [berkshelf/berkshelf#1302]
Let's imagine we have the following in our Berksfile

```
cookbook "some-cookbook", git: "git://github.com/some/repo.git", rel: "folder"
```

And it that repository let's imagine you do have two files with names MyFile.txt and myfile.txt.

In the case insensitive file systems this is the same file. So when try to

```
berks install
```

You will get the following error:

```
Fetching 'some-cookbook' from git://github.com/some/repo.git (at master/some-cookbook)
Git error: command `git filter-branch --subdirectory-filter "some-cookbook" --force` failed. If this error persists, try removing the cache directory at '/my/home/.berkshelf/.cache/git/sfd76fsd7f6sdf7sd6f'.Output from the command:

Cannot rewrite branches: You have unstaged changes.
```

Not sure how it's supposed to be fixed. But I am pretty sure it's should has more informative error at least.

**Comment by franklinwise** [comment]
I'm having this same problem and trying to resolve it. I haven't dug into the issue at all, but why not just copy or move the folder instead of trying to mess with the git history?

**Comment by franklinwise** [comment]
actually mine's different 

```
    stderr: Git error: command `git filter-branch --subdirectory-filter "chef/consul-kio" --force` failed. If this error persists, try removing the cache directory at '/Users/wise/.berkshelf/.cache/git/a03e8019b84c22a55964321de1b97ff5ba29fae1'.Output from the command:

Found nothing to rewrite
```

**Comment by franklinwise** [comment]
actually mine is different 

```
    stderr: Git error: command `git filter-branch --subdirectory-filter "consul-kio" --force` failed. If this error persists, try removing the cache directory at '/Users/wise/.berkshelf/.cache/git/a03e8019b84c22a55964321de1b97ff5ba29fae1'.Output from the command:

fatal: failed to unpack tree object 23d7b2e631232e26f3c01cc34420d09576507f49:consul-kio
Could not initialize the index
```

**Comment by franklinwise** [comment]
looks like mine was because I had a git sub repo and deleted it.

**Comment by styk-tv** [comment]
I can replicate this with berks install if a git repo has unreachable entries and usinf ref at the same time.
```
git fsck --unreachable HEAD $(cat .git/refs/heads/*)
cat: .git/refs/heads/*: No such file or directory
Checking object directories: 100% (256/256), done.
Checking objects: 100% (9758/9758), done.
unreachable commit 470dd7f0c03b11b0490b86f062741597485cabfc
unreachable blob 39188fa30fb6751f5239ace36621c5883a94bcdd
unreachable blob 50252dbc68876006e2146897c7768ba58d443742
unreachable commit db36a32cccde0bff8a679e70cf577532510ed249
unreachable blob bcb98ef4dd6fde4bf9c10db192a30d97f01413b6
unreachable blob 2b439d2c3afdec4a8ab87c9348f388a3ffd72393
unreachable commit fb5bc0a1f3e52271a7a83f0e4880f286c4e91382
unreachable blob 53e4e87ace812d091bddefb8a700f1c9c6fc1229
```

results in

```
Git error: command `git filter-branch --subdirectory-filter "cookbooks/windows" --force` failed. If this error persists, try removing the cache directory at '/home/user1/.berkshelf/.cache/git/0ce63cc1314c5fdfa0ff5887a49ef96e254500c8'.Output from the command:

fatal: failed to unpack tree object d7b4abde042013e9e89beb0c1a00f0595b1b4e37:cookbooks/windows
Could not initialize the index
```

**Comment by llibicpep** [comment]
@sethvargo, @reset 

This old issue brought to my attention once again and I feel like I did not enough to explain why this is actually a berkshelf issue, and why it should be kinda fixed.

From the http://berkshelf.com/ docs:

> An optional rel key can be specified if your repository contains many cookbooks in a single repository under a sub-directory or at root.
> ```
> cookbook "rightscale", git: "https://github.com/rightscale/rightscale_cookbooks.git", rel: "cookbooks/rightscale"
> ```
> This will fetch the cookbook rightscale from the specified Git location from under the cookbooks sub-directory.

My expectation (I assuming I am not alone here) is that berkshelf will:
1. Use git client to clone repo (probably specific branch/tag/ref)
2. Get ```rel``` path from it and put to the destination folder

If I can clone that repo manually I expect no issues when Berkshelf does this. Especially if that repo is not under my control, or for some other reason I can't make changes here and not familiar with the content (in my experience very often you have some common company-wide cookbooks like hardening, that is supported by other teams and you are obligated to use it). Taking in a count things like filter-branch is not something people do in their day-by-day activities, so may be not familiar how it works under the hood. Even for me it is not clear why filter-branch is used here instead of plain I/O operation provided by OS/FS (yeah, I mean ```FileUtils.cp_r```). And, even when you know what is filter-branch and how it works, even without berkshelf, when you just doing plain filter-branch with git on your own purpose, explained case at the very start might be so painful to debug. Especially, again, when the target repo isn't familiar to you.

So, what changes I propose? Really, ```FileUtils.cp_r```. Well, if there is some good reasons to use filter-branch, at least two changes required there in my POV:
1. Clear statement in the docs that filter-branch is used when ```rel``` (and why)
2. Clear output when error comes

Clarification on the second one: raw git output isn't enough when you don't know the context of what has been done here under the hood. Git also has no clue was it called by berkshelf, a human, or something else. I literally have no idea how to improve the output here, but again, it is not clear. Think about it as you are just a berkshelf user, a newbie, and you trying to add some 3rd party cookbook from github with some ```rel```. How much frustration you will get with such a simple use case? I am thinking now - what might have saved time for me a year ago? Hmmm... probably a WARN message with a link to that issue when [git.rb#L62](https://github.com/berkshelf/berkshelf/blob/v3.1.5/lib/berkshelf/locations/git.rb#L62) fails. Something like Chef doing for [CHEF-3694](https://tickets.opscode.com/browse/CHEF-3694). Or, probably, someone will have a better idea?
