### ISSUE TITLE
Local cache and decomissioning version of cookbook in supermarket

### ISSUE THREAD

**Issue by cliffpracht** [berkshelf/berkshelf#1361]
As I understand it, `berks` will keep cookbook versions in local cache of all cookbooks that were previously used.    

Now in the case where we want decommission a cookbook or version of cookbook (in Supermarket),   we would like for `berks install` to fail (Eg not use local cache). 

How does `berks install` handle this situation?  

I suppose we could do a `rm -rf` to cache folder, but that seems not very elegant and could be problematic especially if there are multiple jobs of berks install running on same system (we are planning to run on Jenkins)..

A flag within berks to ignore local cache would be ideal (like `gem install` has an option -r, -​-remote - Restrict operations to the REMOTE domain)  http://guides.rubygems.org/command-reference/#gem-install

Cliff

**Comment by agperson** [comment]
Just want to comment that I ran into this unexpected behavior today.  A user locally modified a community cookbook and bumped the version, then uploaded it to our Chef server.  Running `berks install` on that repository pulled down the new version because the local Berkshelf API server was specified as a source in that repository's Berksfile.

However, when running a `berks install` on a different cookbook repository with a Berksfile that *did not* specify the internal API server as a source, the "new" cookbook was still picked up from local cache, even though it conflicts with the version reported by the API source (i.e. the public Supermarket).  This broke the cookbook in a very confusing way.

It doesn't seem like this should be the expected behavior in the case where multiple API servers might be in use.
