### ISSUE TITLE
Where to begin ...

### ISSUE THREAD

**Issue by swade1987** [berkshelf/berkshelf#1371]
I have an application which is made up of

Some ASP.NET MVC websites
Some WCF webservices
A few MS SQL databases

Note: We want to use Chocolatey packages to do the deployments.
Note: We have the same services running on multiple VMs within the same environment.
Note: We have the following environments - CI, SysTest, UAT and Prod

1. Is this one massive cookbook or a cookbook per component?

2. Without using roles or environments how does Chef know how to deploy version X of the application to the necessary servers in UAT for example?.

**Comment by sethvargo** [comment]
Hi @swade1987 

Thank you for reaching out. This issue seems to be much larger than Berkshelf and includes some Chef-specific questions. I would recommend asking on the Chef mailing list or in the Chef IRC room for a more detailed answer.


> 1. Is this one massive cookbook or a cookbook per component?

In general, you want one cookbook per application

> 2. Without using roles or environments how does Chef know how to deploy version X of the application to the necessary servers in UAT for example?

Without more context, you lock the version of the application in the cookbook (maybe to an SCM SHA or binary release). So cookbook version x.y.z releases version x.y.z of the application.
