### ISSUE TITLE
'berks update' does not resolve recursive dependencies

### ISSUE THREAD

**Issue by tpetchel** [berkshelf/berkshelf#1404]
(Apologies if this is a dup of #1265.)

When running `berks update`, I would expect all recursive dependencies to be resolved. I found that I had to run `berks update` more than one time for everything to resolve.

Repro steps:
1. Ensure your Berks cookbook cache (`~/.berkshelf/cookbooks`) is empty
2. Create a new cookbook
   
   ``` bash
   $ chef generate cookbook cookbooks/foobar
   ```
3. `cd` to cookbook dir
   
   ``` bash
   $ cd cookbooks/foobar
   ```
4. Do initial `berks install`
   
   ``` bash
   $ berks install
   Resolving cookbook dependencies...
   Fetching 'foobar' from source at .
   Fetching cookbook index from https://supermarket.chef.io...
   Using foobar (0.1.0) from source at .
   ```
5. Add a dependency on the `mysql` cookbook. 
   
   ``` ruby
   name             'foobar'
   maintainer       'The Authors'
   maintainer_email 'you@example.com'
   license          'all_rights'
   description      'Installs/Configures foobar'
   long_description 'Installs/Configures foobar'
   version          '0.1.0'
   
   depends 'mysql', '~> 6.0.17'
   ```
6. Run `berks update`
   
   ``` bash
   $ berks update
   Resolving cookbook dependencies...
   Fetching 'foobar' from source at .
   Fetching cookbook index from https://supermarket.chef.io...
   Using foobar (0.1.0) from source at .
   Installing yum (3.5.3)
   Installing mysql (6.0.17)
   Installing smf (2.2.5)
   Installing rbac (1.0.2)
   Installing yum-mysql-community (0.1.14)
   ```
7. Run `berks update` a second time
   
   ``` bash
   $ berks update
   Resolving cookbook dependencies...
   Fetching 'foobar' from source at .
   Fetching cookbook index from https://supermarket.chef.io...
   Using foobar (0.1.0) from source at .
   Installing resource-control (0.1.1)
   Using yum (3.5.3)
   Using yum-mysql-community (0.1.14)
   Using mysql (6.0.17)
   Using rbac (1.0.2)
   Using smf (2.2.5)
   ```

Note that `resource-control` was installed on the second run. I would have expected everything to resolve on the first run.

If this is expected behavior, can someone explain what the preferred workflow is for ensuring all deps are resolved?

**Comment by lamont-granquist** [comment]
The `smf` cookbook is pulling in `resource-control` via a `recommends` line instead of a `depends` line.

The fact that `recommends` and `suggests` were never implemented but people seem to be using them as 'documentation' is most likely terrible since whenever we do implement them we'll break people who think the semantics of them should be different from whatever we choose.

Aside from that berkshelf should probably either consistently ignore `recommends` or consistently treat it as a hard dependency.  There might be a supermarket bug here as well, i'm not sure what /universe returns there for for recommends.

**Comment by lamont-granquist** [comment]
And there is a berks bug here since:

```
berks update && berks upload
```

Will fail since it doesn't download resource-control but does try to upload it and can't find it.  While this works:

```
berks update && berks update && berks upload
```

So something berks is doing to handle recommends is inconsistent (and/or supermarket?)

**Comment by reset** [comment]
@lamont-granquist Berkshelf is supposed to handle recommends the same as depends. I think we broke it somewhere during a refactor.

**Comment by tpetchel** [comment]
Just FYI, a change was made today to the `smf` cookbook that invalidates the repro case. The core issue   remains.

**Comment by lamont-granquist** [comment]
Not sure if this bug still exists or not, the solution of not using 'recommends' or 'suggests' though since their semantics in core chef have never been defined is still correct though.

We should probably warn on 'recommends' or 'suggests' in berkshelf like we do in foodcritic, but closing this issue for now.
