### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by BackSlasher** [berkshelf/berkshelf#1411]
I admit this is an edge case, but:
Vagrant uses the Berkshelf plugin to vendor cookbooks to the VM. If no cookbooks are explicitly mentioned in the Berksfile (`cookbook bla`), nothing is vendored to the VM.
Since Vagrant knows the primary cookbooks (can be extrapolated from whatever `chef.add_recipe` statements affect), it can pass that to Berkshelf. However, Vagrant uses the Berkshelf binary (and not some custom ruby code) for vendoring, so the Berksfile has to be modified to include said cookbooks.
I think modifying an existing Berksfile on-the-fly is a bad idea, so I thought Berkshelf could be modified to accept multiple Berkfiles, one of which will be the original, and another generated by Vagrant and containing the cookbooks from the Vagrantfile.
Your opinion? Is there a better solution I'm missing?

**Comment by sethvargo** [comment]
> If no cookbooks are explicitly mentioned in the Berksfile (cookbook bla), nothing is vendored to the VM.

That is the expected behavior.

> Since Vagrant knows the primary cookbooks (can be extrapolated from whatever chef.add_recipe statements affect), it can pass that to Berkshelf.

That's not true. Vagrant has multiple initialization phases and Berkshelf does _not_ know those values yet (they have not even been computed yet).

>  However, Vagrant uses the Berkshelf binary (and not some custom ruby code) for vendoring, so the Berksfile has to be modified to include said cookbooks.

It used to vendor all of Berkshelf, but that turns out to be an incredibly painful installation experience.

> I think modifying an existing Berksfile on-the-fly is a bad idea

Yup

>  I thought Berkshelf could be modified to accept multiple Berkfiles

If you add something like this to your parent Berksfile, it will work:

```ruby
source "..."
# ...

instance_eval(File.read("Berksfile.2"))
```

But I am against adding first-class support for something like this. The Berksfile + lockfile is designed to describe the current state of your infrastructure.

**Comment by BackSlasher** [comment]
So to sum up, this wouldn't help the vagrant plugin anyway because it's running too early?

**Comment by sethvargo** [comment]
Yup :smile:
