### ISSUE TITLE
Berkshelf should not require $HOME to be set

### ISSUE THREAD

**Issue by eric-tucker** [berkshelf/berkshelf#1427]
When running Berks through CFN:

````
"berks vendor --berksfile=zero/Berksfile berks-cookbooks\n",
````
The command will fail if $HOME is not set.  This is obviously wrong as environment variables specific to a user should not be required for running any command.

**Comment by sethvargo** [comment]
@eric-tucker Berkshelf installs cookbooks into `$HOME/.berkshelf`. You can customize this by setting the `BERKSHELF_PATH` environment variable, but the default is a user-install, which requires the $HOME variable to be set.

**Comment by eric-tucker** [comment]
Really?  Closed?

Have you ever heard of unattended installs?  CloudFormation?  Automation?  Environment variables go against that mantra.

Using CloudFormation and installing through the Chef DK, berks should be able to function without environment variables set.

You'll also notice that I'm NOT interested in installing the cookbooks - I don't want them vendored.  Perhaps the vendor option should not be installing cookbooks to $HOME/.berkshelf.  I thought this was the point of the vendor option: to simply download the cookbooks to a specified location.

**Comment by sethvargo** [comment]
Hi @eric-tucker 

I am sorry you are upset, but there is no need to take a hostile tone. I apologize if I have upset you. Berkshelf works by installing cookbooks into your home directory and then copying the appropriate values into the specified vendor directory. That process is deeply rooted into the core of Berkshelf and would not be trivial to change.

> Using CloudFormation and installing through the Chef DK, berks should be able to function without environment variables set.

I disagree, and you should not be installing the ChefDK or running Berkshelf in production. You should compile cookbooks locally and then upload the package. You should not be berkshelfing cookbooks in production the same way you should not compile binaries in production.

> You'll also notice that I'm NOT interested in installing the cookbooks - I just want them vendored.

You can vendor them locally, into a directory on your _local_ machine, and then upload only that vendored directory as part of your cloud formation installation.

**Comment by eric-tucker** [comment]
>I am sorry you are upset, but there is no need to take a hostile tone. I apologize if I have upset you. 

What upset me was immediately closing the item without any discussion.  Simply stating "that's the way it works" and closing the issue is not going to garner a positive response.

^Berkshelf works by installing cookbooks into your home directory and then copying the appropriate values into the specified vendor directory. That process is deeply rooted into the core of Berkshelf and would not be trivial to change.
Then why do you have the BERKSHELF_PATH environment variable?  If you were to simply expose this as a command line option then that would be EXACTLY what I'm looking for and how I thought vendor worked.

> I disagree, and you should not be installing the ChefDK or running Berkshelf in production. You should compile cookbooks locally and then upload the package. You should not be berkshelfing cookbooks in production the same way you should not compile binaries in production.

We build AMIs in advance using CloudFormation, Chef (zero) and Berkshelf.  That is our "package".  We don't do packages like tgz files or whatever other suggestion you're making because that's not the way it's supposed to be done in AWS with autoscaling.  In a way we are still packaging outside of production and deploying that package to production.  We never run Berkshelf as part of a life deployment.

Also, to me, to suggest that a USER should be packaging things that are going to go production demonstrates a lack of experience with proper deployment strategies.  Nothing compiled or packaged by a user should ever go to production.  You always have Operations managed systems do packaging or deployment using repeatable work units.

Off topic though.  I would rather not get into a philosophy discussion with you on proper DevOps practices.

>You can vendor them locally, into a directory on your local machine, and then upload only that vendored directory as part of your cloud formation installation.

Define "upload only that vendored directory."  Are you suggesting packaging cookbooks that berks would otherwise put to my vendored path, placing to S3 and then downloading that package as part of CloudFormation?

Regardless, since we use pre-baked AMIs this is unnecessary.

**Comment by sethvargo** [comment]
Okay. I was trying to be nice, but now you're being rude and calling me inexperienced. I would suggest you read over [Chef's community guidelines](https://docs.chef.io/community_guidelines.html) before treating maintainers with such disrespect. I understand that you are upset, but there is no need to be hostile or yell in ALL CAPS.

First, you are putting words in my mouth and making assumptions. I'm not suggesting a user would do these things, I am trying to provide examples to encourage you to think differently. I am very familiar with DevOps practices, so let's not even go there :smile:.

> What upset me was immediately closing the item without any discussion. Simply stating "that's the way it works" and closing the issue is not going to garner a positive response.

Your original issue mentioned none of the details you later mentioned. In short, it was "why do I need to $HOME to be set?". I answered that question, and therefore closed the issue. Had you provided a more detailed explanation in the original issue, there could have been more of a discussion. I am sorry that you feel if I was being dismissive - that's not the case. I thought I answered your minimal question, but now there are _many_ other pieces you have brought into the equation, so I will re-open it :smile:.

> Then why do you have the BERKSHELF_PATH environment variable? If you were to simply expose this as a command line option then that would be EXACTLY what I'm looking for and how I thought vendor worked.

Without getting too much into the details of Berkshelf, exposing this as a CLI option is not possible. Due to the way Berkshelf loads, it needs to know it's working directory _before_ the CLI is even invoked. Environment variables are quite common in Ruby tools for these types of configuration options that cannot be CLI-based. In fact, we borrowed the configuration option from [Bundler](http://pickardayune.com/blog/2012/05/04/bundler-environment-variables/) and [Vagrant](http://docs.vagrantup.com/v2/other/environmental-variables.html). Environment variables are very common. Your tone makes it sound like we just woke up one morning and said "how can we make @eric-tucker's life more difficult", but I promise that's not the case.

> Define "upload only that vendored directory." Are you suggesting packaging cookbooks that berks would otherwise put to my vendored path, placing to S3 and then downloading that package as part of CloudFormation?

I am suggesting that your build server (jenkins, circle, etc) would be responsible for packaging all cookbooks in a Berksfile.lock into a tarball. That tarball is then uploaded and extracted by CloudFormation, and Chef is run against that set of cookbooks. In fact, we made an entire command `berks package` that does exactly that for you :smile:. Of course this just one solution to the problem.

Lastly, Berkshelf is an open source tool. If there is something you would like to change, you are always welcome to submit a Pull Request.

**Comment by eric-tucker** [comment]
> Okay. I was trying to be nice, but now you're being rude and calling me inexperienced. I would suggest you read over Chef's community guidelines before treating maintainers with such disrespect. I understand that you are upset, but there is no need to be hostile or yell in ALL CAPS.

I never yelled by typing in all caps.  I put certain words in caps for emphasis as opposed to using bold because I was in a hurry.  I apologize for the disrespect.  However, there is no need to share a list of common sense rules to me.  Regardless of rules, I'm not going to react positively when I feel my concerns are being immediately dismissed with no explanation.

> First, you are putting words in my mouth and making assumptions. I'm not suggesting a user would do these things, I am trying to provide examples to encourage you to think differently. I am very familiar with DevOps practices, so let's not even go there :smile:.

Be clear then.  When I am told that I shouldn't be installing ChefDK or Berks in prod and that I should "compile cookbooks locally and then upload the package" my first thought is that you're suggesting my methods are wrong and that we should change our whole deployment strategy because you don't wish to change Berks.  So naturally I'm going to take offence.

Yes I have been hostile, but that was triggered by your immediate dismissal of my issue.

> Your original issue mentioned none of the details you later mentioned. In short, it was "why do I need to $HOME to be set?". I answered that question, and therefore closed the issue. Had you provided a more detailed explanation in the original issue, there could have been more of a discussion. I am sorry that you feel if I was being dismissive - that's not the case. I thought I answered your minimal question, but now there are many other pieces you have brought into the equation, so I will re-open it :smile:.

My issue did not ask a question.  I stated that requiring $HOME to be set was wrong.  I don't care WHY it works that way now, I'm telling you that's wrong.  User specific variables should not be required to run commands unattended where no user is logged in.  It matters not that you think I shouldn't be running Berkshelf the way I am doing it.  It is my opinion that it is bad practice for any command to require a user home directory be set in order to function, especially when that command should function without an active shell.  Imagine if, for example, the "rm" command needed a HOME variable because it was hard coded to move files to $HOME/.trash?

To me, Berks should follow the same mantra as npm or gem executions where an option is present (or is the default) to install the dependencies specified by the dependency file (npm package list, gem list) at a global level.  Berks should act as a dependency management system but it seems you wish to treat it specifically as a build tool for development.  Why is it we can't have the best (or part) of both worlds?

> Without getting too much into the details of Berkshelf, exposing this as a CLI option is not possible. Due to the way Berkshelf loads, it needs to know it's working directory before the CLI is even invoked. Environment variables are quite common in Ruby tools for these types of configuration options that cannot be CLI-based. In fact, we borrowed the configuration option from Bundler and Vagrant. Environment variables are very common.

This explanation I can understand.

> Your tone makes it sound like we just woke up one morning and said "how can we make @eric-tucker's life more difficult", but I promise that's not the case.

I didn't suggest you did this.  It was your immediate dismissal of my item that triggered my hostile attitude.  Had you replied how you did without closing my item and perhaps asked for more feedback on my use case I wouldn't have felt like you were simply ignoring my concerns and moving on.

> I am suggesting that your build server (jenkins, circle, etc) would be responsible for packaging all cookbooks in a Berksfile.lock into a tarball. That tarball is then uploaded and extracted by CloudFormation, and Chef is run against that set of cookbooks. In fact, we made an entire command berks package that does exactly that for you :smile:. Of course this just one solution to the problem.

I am open to a suggestion such as this.  I don't disagree that this is a good solution and I will definitely consider it.  I am always open to suggestions on how to improve our deployment methodologies but please try to present them in a better way than "you shouldn't be doing that" (your comment regarding installing Berks and ChefDK in production).

> Lastly, Berkshelf is an open source tool. If there is something you would like to change, you are always welcome to submit a Pull Request.

I would consider doing this but I would need some instructions on how to build the gem and deploy to a server for testing.

I am sorry that this issue/thread had to turn into something so hostile that accomplishes very little.  I admittedly overreacted to your immediate closure of my issue.  For that, I apologize.

**Comment by reset** [comment]
@sethvargo did a great job handling this issue so I normally wouldn't feel the need to weigh in, but this is a particularly heinous issue *even* for the Berkshelf tracker, so here we go.

Open source maintainers get a lot of issues in the form of a question, feature/bug requests which sound like "I like this apple but could you make this apple an orange? It would be a lot better if it were an orange.". When an issue is closed it isn't the end of the discussion, it's the end of the current step of triage. It's an end to any additional noise for the moment. It goes without saying that there is a re-open button for a reason.

We also get a lot of issues like this one where people are **certain** that they are correct and create an issue without much explanation on why. The why is really important because it helps the maintainer frame the idea and continue the conversation in a constructive way. Something very useful could often come across as pointless because the correct context just wasn't given. If you have a use case for the tool that you're using which isn't covered, explain as much as you possibly can upfront and understand that another human being is going to read and respond to your issue.

I am not sure what part of the world you came from where you think insulting somebody providing you with assistance is going to help you move your personal agenda further, but I would avoid doing so to any of the people maintaining any open source projects that you're consuming.

Why don't you try again. Create an issue clearly stating the problem that you are having, **sans asshole prose**, and provide the context for the issue. Suggest an appropriate fix which doesn't alter the behaviour of the tool in a way that turns the "apple into an orange" and then a maintainer of this project will respond to the issue completely ignoring that this one **ever** happened. Then we can work on helping you to understand how to build/test the gem and form a pull request to contribute back into the project.
