### ISSUE TITLE
Feature for local install

### ISSUE THREAD

**Issue by aiionx** [berkshelf/berkshelf#1446]
I have cookbooks that use cookbooks of my own.

I usually have to install them like:
    `cp -r ese-jupiter ~/.berkshelf/cookbooks/ese-jupiter-0.2.0`

In order for cookbooks that depend on this cookbook to compile during integration tests.

is there something like...
    $ cd ese-jupiter
    $ berks local-install

So it gets installed in
   `~/.berkshelf/cookbooks/ese-jupiter-0.2.0`
or whatsoever major/minor/patch version is described in the metadata.rb file.

Thanks

**Comment by sethvargo** [comment]
You can use `:path` to refer to local cookbooks

**Comment by aiionx** [comment]
Yes, but that is disruptive to your Berksfile.

A build lifecycle like maven does is not disruptive.

You locally install, do your integration tests, and if you like what you have push it to supermarket to share with other members of your team.

This is how they do it in the install goal:
install - install the package into the local repository, for use as a dependency in other projects locally
https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

**Comment by sethvargo** [comment]
Have you read [this post](https://sethvargo.com/berkshelf-workflow/)?

I'm not sure how that is "disruptive" to your Berksfile - I'd be interested to hear more about that. Usually the workflow is this:

- Develop locally
- Test locally
- Test in CI
- Successful CI produces artifact
- Upload artifact to repo (supermarket in this case)

You can use `berks vendor` to vendor the cookbooks inside the cookbook or `berks package` to create a tarball of the dependent cookbooks.

If cookbook A depends on B and cookbook C depends on B, then A is a transitive dependency of C. Thus adding B as a dependency in the metadata of C will implicitly pull in A, so I don't understand the issue here.

**Comment by aiionx** [comment]
Here i am about resolving those dependencies.

It works if I have a snapshot version published at supermarket and Berks resolves from there.

But I would expect that during the "Develop locally" phase I can have the in-house developed dependency cookbooks somewhere that is resolvable (like `~/.berkshelf/cookbooks`) before having them as snapshots in supermarket or anywhere else. That is, resolving dependencies locally of in-progress dependencies.

i cant discuss if this is part or not part of the CI, or if is or not a good practice. I just say this because it is possible in maven.

**Comment by aiionx** [comment]
In an analogy, just like `berks upload` uploads the dependencies and current cookbook to chef.
`berks install` could install the dependencies and current cookbook to `~/.berkshelf/cookbooks`

**Comment by thommay** [comment]
We are treating berkshelf as feature complete at this time; if you'd like to submit a PR then we'd gladly review it, but we're not undertaking any further work ourselves. 
I'm going to close this ticket, thanks for your interest.
