### ISSUE TITLE
Unit tests fail on master due to new celluloid.

### ISSUE THREAD

**Issue by ksubrama** [berkshelf/berkshelf#1448]
```
Failed examples:

rspec ./spec/unit/berkshelf/resolver/graph_spec.rb:15 # Berkshelf::Resolver::Graph#populate adds each dependency to the graph
rspec ./spec/unit/berkshelf/resolver/graph_spec.rb:20 # Berkshelf::Resolver::Graph#populate adds the dependencies of each dependency to the graph
rspec ./spec/unit/berkshelf/resolver/graph_spec.rb:34 # Berkshelf::Resolver::Graph#universe returns an array of APIClient::RemoteCookbook
rspec ./spec/unit/berkshelf/resolver/graph_spec.rb:40 # Berkshelf::Resolver::Graph#universe contains the entire universe of dependencies
```

```
  1) Berkshelf::Resolver::Graph#populate adds each dependency to the graph
     Failure/Error: Unable to find matching line from backtrace
     Berkshelf::APIClient::ServiceUnavaiable:
       Connection refused - connect(2) for "localhost" port 26210 (http://localhost:26210)
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/source.rb:22:in `build_universe'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/source.rb:36:in `universe'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/resolver/graph.rb:53:in `block in universe'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/resolver/graph.rb:53:in `each'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/resolver/graph.rb:53:in `universe'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/lib/berkshelf/resolver/graph.rb:36:in `populate'
     # /Users/ksubramanian/repo/berkshelf/berkshelf/spec/unit/berkshelf/resolver/graph_spec.rb:16:in `block (3 levels) in <top (required)>'
```

I have bisected all your dependencies and pinning celluloid to 0.16.0 in the Gemfile seems to resolve the issue.

**Comment by adamedx** [comment]
A fix here as soon as its feasible would be highly appreciated as we are using bundler in our build process in order to vendor berkshelf. The Celluloid issue is a transitive dependency for us, so we don't have an easy way to pin it to 0.16.0. 

We're concerned that 0.16.1 is riskier than its version suggests, since the diff between it and the previous patch version is fairly significant:
https://github.com/celluloid/celluloid/compare/v0.16.0...v0.16.1

The test failure we're seeing may be a real bug given the number of changes between those releases. Pinning back to 0.16.0 seems like the safest fix unless 0.16.1 is addressing some sort of security issue.

**Comment by reset** [comment]
I was able to reproduce this but haven't looked into it yet. Not sure what changed in 0.16.1. We can hard lock to 0.16.0 in the mean time.

**Comment by ksubrama** [comment]
There hasn't been a new release but celluloid has yanked the 0.16.1 gem from rubygems - so we can still use the current berkshelf *fingers crossed*
