### ISSUE TITLE
Berkshelf install --except option not working

### ISSUE THREAD

**Issue by suharshan** [berkshelf/berkshelf#1468]
I'm using berkshelf version 3.2.4. I have created a group as follows in my Berkshelf file.

`group :mfs do`
`  cookbook 'git'`
`end`

Then I issue the following command to install my dependencies.
`berks install --except mfs`

This command is supposed to download every other cookbook except git (in my case only tomcat-all is there). But it downloads git as well. 

But if I change my group as following and execute `berks install --only mfs`, it downloads only the git cookbook as expected.

`group :mfs do`
`  cookbook 'tomcat-all'`
`end`

Following are my complete  Berksfile and metadata.rb files.

##### Berksfile
```
source "https://supermarket.chef.io"

metadata

group :mfs do
  cookbook 'git'
end
```

##### metadata.rb
```
name             'mfs-tomcat'
maintainer       'DirectFN'
maintainer_email 'p.pubudu@directfn.com'
license          'All rights reserved'
description      'Installs/Configures bo-tomcat'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'tomcat-all'
depends 'git'
```

**Comment by reset** [comment]
@suharshan this is happening becuase you also have the `git` dependency inside the metadata of your cookbook. It will override whatever group you've placed it into since the metadata will take precedence.

By placing the dependency in your metadata you are saying that it is a "top level dependency" and it is not part of a group. If `git` is a development or testing dependency then you should place it in a group inside your Berksfile. If it is not, then you should remove that group and leave it as is.

**Comment by suharshan** [comment]
Thanks a lot for the detailed explanation @reset .
