### ISSUE TITLE
Recognize certificates from ChefDK trusted_certs path

### ISSUE THREAD

**Issue by jmccann** [berkshelf/berkshelf#1470]
This would be helpful as I've ran into issues when using a private supermarket to download cookbooks from it without disabling SSL.

With knife I can simply run `knife ssl fetch` and my knife commands will work properly with my supermarket server.  However Berkshelf continues to not work.

It was mentioned in https://github.com/chef/chef-dk/issues/514 that I could try opening an issue here to have Berkshelf recognize certificates that are in `~/.chef/trusted_certs` which is where `knife ssl fetch` puts certificates.

**Comment by StephenKing** [comment]
:+1:

**Comment by louis-gounot** [comment]
From my understanding, it would require to add an ssl.cert_store_dir option.
If missing, works as now.
If present : 

- An OpenSSL::X509::Store must be instanciated
- default_paths (see OpenSSL::X509::Store doc) should be added to this store
- cert_store_dir should be added to it
- add :cert_store with this new OpenSSL store added to :ssl options
- remove :cert_store_dir from :ssl options


Should the config.rb be the best location to do this (my favorite) or would we update downloader.rb and uploader.rb ?
I can implement it quickly if this is OK.

**Comment by louis-gounot** [comment]
Could also be easier to use directly ca_path option for Net::HTTP (need to check if it works properly).
By the way, from what I remember, berkshelf does not use knife.rb directly, it uses it's own config for chef config. In case it is not provided, it fallback to what Ridley does.

**Comment by reset** [comment]
@louis-gounot that suggestion seems sound to me. If you'd like to add the functionality I'll happily merge it in!

**Comment by louis-gounot** [comment]
@reset Ok. I'll do it next week I think

**Comment by louis-gounot** [comment]
Hello.
Well, I was not able to work on this as I expected.
1 additional question regarding this : is it acceptable to use the chef-config gem to fetch the knife.rb config file the same way knife does (chef-config gem has much less dependencioes than Chef itself).
I believe it will be more user friendly to rely on knife.rb config file instead adding duplicate configuration in berkshelf config file.
My idea is to use chef-config gem to fetch Chef related config and inject it back in berks config through the API.

**Comment by howdoicomputer** [comment]
Is this abandoned? If so, I wouldn't mind doing the work for it. The common advice I'm seeing around the internet for Berkshelf is to just turn off SSL verification all together and that's... not good.

**Comment by thommay** [comment]
@howdoicomputer we'd be very happy for you to do this work. To answer @louis-gounot's question above, Berkshelf already loads chef's config file - https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf.rb#L90-L92 - so you can use that to get the ssl path.

**Comment by howdoicomputer** [comment]
@thommay Alrighty. I'll see what I can do. If anybody comes across this thread and is willing to offer some snazzy advice then I'd be pretty grateful.

**Comment by howdoicomputer** [comment]
Okay, so I got the basics working and opened up a pull request. it is not close to ready for merging but I wanted to get feedback early on before I go forward too far. if I stepped outside of bounds by submitting a PR before my feature is tested then feel free to close it and I'll go do that.

I based my code somewhat off the code that [knife uses](https://github.com/chef/chef/blob/db57131ad383076391b9df32d5e9989cfb312d58/lib/chef/http/ssl_policies.rb) to pull in certs from the trusted certificate directory.

I have a lot left to do. One problem I have, however, is that although Berkshelf is loading the Chef configuration file... it is using Ridley to parse out the attributes. This is somewhat of a problem since Ridley doesn't pick up on the `trusted_certs_dir` - so I may have to open up a PR against Ridley as well.

Right now I'm just testing by building the gem locally and communicating with my company's internal Chef server.

```
⋊> ~/w/w/c/tl_jenkins_cookbook on master ⨯ /Users/thampton/workspace/personal/berkshelf/bin/berks upload      21:29:36
Skipping apt (5.0.0) (frozen)
Skipping build-essential (7.0.1) (frozen)
```

Compared to:

```
⋊> ~/w/w/c/tl_jenkins_cookbook on master ⨯ berks upload                                                       21:29:27
E, [2016-10-25T21:29:36.661995 #98830] ERROR -- : Ridley::Errors::ClientError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

I'll follow through with tests, yardoc documentation, and edge case handling over the next couple days but... does the basics of what I'm doing look okay as far as code quality and implementation method? My code doesn't really *feel* right at all and I'm a bit of a perfectionist. @thommay

**Comment by howdoicomputer** [comment]
I totally lied about that `trusted_certs_dir` attribute. The reason why I had arrived at the false conclusion that Ridley didn't support that attribute was because of this test output:

```
  7) Berkshelf::Uploader#run when a client key is passed as an option uses the passed in :client_key
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       #<Double Ridley::Chef::Config> received unexpected message :trusted_certs_dir with (no args)
```

After adding this block to `config.rb`:

```
    attribute 'trusted_certs_dir',
      type: String,
      default: Berkshelf.chef_config.trusted_certs_dir
```

That was really just RSpec failing because of a mismatched `expect`. Guess I needed some sleep.

I do need to mock a key store to pass in to the Ridley connection constructor in order to get this test to pass:

```
        it 'uses the Berkshelf::Config options' do
          skip 'need to mock an keystore for this test to work' do
            expect(Ridley).to receive(:open).with(
              server_url:  chef_config.chef_server_url,
              client_name: chef_config.node_name,
              client_key:  chef_config.client_key,
              ssl: {
                verify: berkshelf_config.ssl.verify
              }
                              )
          end
```

**Comment by howdoicomputer** [comment]
Alright, I'm stuck.

```
        it 'uses the Berkshelf::Config options' do
          expect(Ridley).to receive(:open).with(
            server_url:  chef_config.chef_server_url,
            client_name: chef_config.node_name,
            client_key:  chef_config.client_key,
            ssl: {
              verify: berkshelf_config.ssl.verify
            }
          )
          subject.run
        end
```

So I was able to get all the other tests to pass by using a certificate fixture and passing that into the `Ridley::Chef::Config` double constructor but the test above is stumping me. I can pass in a `cert_store` fixture but the object ids will be different for the stores. I'll get something like this if I do so:

```
       -     #<OpenSSL::X509::Store:0x007fcbffbeead8 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil, @_httpclient_cert_store_items=[:default, #<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x007fcc00c48438>, issuer=#<OpenSSL::X509::Name:0x007fcc00c48410>, serial=#<OpenSSL::BN:0x007fcc00c483e8>, not_before=2013-10-17 18:01:35 UTC, not_after=2023-10-15 18:01:35 UTC>]>}}]
       +     #<OpenSSL::X509::Store:0x007fcc00988860 @verify_callback=nil, @error=nil, @error_string=nil, @chain=nil, @time=nil, @_httpclient_cert_store_items=[:default, #<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name:0x007fcbffeb7030>, issuer=#<OpenSSL::X509::Name:0x007fcbffeb7008>, serial=#<OpenSSL::BN:0x007fcbffeb6fe0>, not_before=2013-10-17 18:01:35 UTC, not_after=2023-10-15 18:01:35 UTC>]>}}]
```

I'll let this sit for a bit since I have work, work stuff to do. If a better Rubyist can help me out then I'd be deeply appreciative. @reset @thommay @StephenKing 

Also, it looks like a couple travis jobs are broken on the dependency install phase? Like [this build](https://travis-ci.org/berkshelf/berkshelf/jobs/170918418)?

**Comment by afiune** [comment]
Making some progress with the last PR! We will get this in soon enough.. Gotta be excited and thank you @howdoicomputer for the heavy lifting! 👍

**Comment by jmccann** [comment]
Awesome work @afiune and @howdoicomputer !  Thanks a ton!
