### ISSUE TITLE
Berkshelf  is failing if we do not include child cookbook dependencies in parent cookbook

### ISSUE THREAD

**Issue by dilippanwar1** [berkshelf/berkshelf#1500]
I have a cookbook with a name hc_users and it is using hc_sudo cookbook  so I have included it in its both metadata and berksfile. 
Now I have another cookbook where I want to include hc_users cookbook. but here I am getting berkshelf error mentioned below-

Unable to satisfy constraints on package hc_sudo, which does not exist, due to solution constraint (hc_users = 0.1.0). Solution constraints that may result in a constraint on hc_sudo: [(hc_users = 0.1.0) -> (hc_sudo >= 0.0.0)]
Missing artifacts: hc_sudo
Demand that cannot be met: (hc_users = 0.1.0)
Unable to find a solution for demands: hc_java (0.1.4), hc_users (0.1.0)

But if I include hc_sudo cookbook as a dependency in my top level cookbook it works fine. 

Can you please look in to it as this is also causing some other issues while recipe execution.

**Comment by inhumantsar** [comment]
This has been a known/won't-fix issue for *three years* now apparently. I've just encountered it myself as well. It will never be fixed for ...reasons?.... See: https://github.com/berkshelf/berkshelf/pull/304

Nested dependencies are a must have feature in my opinion. Considering that they work for community cookbooks, it seems that the community agrees in general. Leaving git-based cookbooks out of that nested resolution is definitely unexpected behaviour and seriously impairs the usefulness of Berkshelf. 

I'm trying to get a Chef Solo-based image build and deploy system rolling but can't do it without nested deps. I'm going to have to write some hacky bullshit to workaround this issue and simulate the feature (if not entirely replace berkshelf...).

**Comment by lamont-granquist** [comment]
Definitely not getting fixed in Berkshelf.  Might get fixed in PolicyFiles.  I do plan on making it easier to work around this problem by using the chef_repo source in PolicyFiles and being able to mix and match with the supermarket source.   If you don't have name collisions between your git cookbook and supermarket cookbooks this already works.  Of course it punts the problem of synchronizing the git sources and requires you to maintain a chef-repo with all your git versions checked out in it, or to have a meta-repo with a bunch of git submodules.  But this isn't getting fixed.

And bundler behaves similarly and does not transitively look up Gemfile's or Gemfile.locks, and there's pretty decent reasons for that.
