### ISSUE TITLE
berkshelf: problems with ruby 2.3.0

### ISSUE THREAD

**Issue by neovatar** [berkshelf/berkshelf#1513]
Setup:
- ruby 2.3.0 installed via rbenv
- berkshelf 4.1.1 installed via gem install
- doing a `berks install` in a project

Lots (multiple times per used cookbook) the following warnings are generated, this is probably caused by httpclient 2.6.0.1:

    /home/tom/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead

Berkshelf then fails with:

    Ridley::Errors::ClientError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

SSL verify is disabled in ~/.berkshelf/config.json

Calling `berks install -d` gives:

    D, [2016-02-15T17:17:06.958292 #22444] DEBUG -- : request env: #<struct Faraday::Env method=:get, body=nil, url=#<Addressable::URI:0x3ffababa0dfc URI:https://chef-1.hst.sznet.de:443/cookbooks/apt/2.9.2>, request=#<Faraday::RequestOptions (empty)>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/json", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Ridley v4.4.2", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"tseliger", "X-OPS-TIMESTAMP"=>"2016-02-15T16:17:06Z", "X-OPS-CONTENT-HASH"=>"removed", "X-OPS-AUTHORIZATION-1"=>"removed", "X-OPS-AUTHORIZATION-2"=>"removed", "X-OPS-AUTHORIZATION-3"=>"removed", "X-OPS-AUTHORIZATION-4"=>"removed", "X-OPS-AUTHORIZATION-5"=>"removed", "X-OPS-AUTHORIZATION-6"=>"removed", "HOST"=>"chef-1.hst.sznet.de:443"}, ssl=#<Faraday::SSLOptions verify=true>, parallel_manager=nil, params=nil, response=nil, response_headers=nil, status=nil>

Seems like faraday tries to use SSL verify, even though it is disabled in berkshelf config

**Comment by benthorner** [comment]
This seems to be an issue since 2.3.0. We're currently stuck on 2.2.2, which still seems to read ~/.berkshelf/config.json.

**Comment by gravitystorm** [comment]
I've tracked down the problem here. Berkshelf can't parse config.json using ruby >= 2.3.0 because of a clash involving `Hash.dig`

* [Berkshelf::Config.initialize calls super](https://github.com/berkshelf/berkshelf/blob/1e731428e994e611a6925d6a13e9aaadbaa99875/lib/berkshelf/config.rb#L62-L63) which is Buff::Config.initialize
* [Buff::Config](https://github.com/reset/buff-config/blob/master/lib/buff/config.rb) includes varia_model
* [varia_model requires buff/extensions](https://github.com/reset/varia_model/blob/master/lib/varia_model.rb#L1)
* buff/extentions [defines Hash.dig](https://github.com/reset/buff-extensions/blob/master/lib/buff/extensions/hash/dotted_paths.rb#L70-L97)

Unfortunately the buff/extensions version of Hash.dig has a different api from the ruby 2.3.0 Hash.dig

buff/extensions:
`nested_hash.dig('deep.nested.hash') => :seed_value`
Ruby 2.3.0 core:
`nested_hash.dig(:deep, :nested, :hash') => :seed_value`

Because of this, Berkshelf on ruby 2.3.0 can't read any nested config options, like ssl.verify

---

I don't know where to go with this next - between berkshelf, buff-config, varia_model and buff-extensions it's not clear to me where the fix should be applied. There are already open issues on varia_model (https://github.com/reset/varia_model/issues/17) and buff-extensions (https://github.com/reset/buff-extensions/issues/6). It's worth noting that @reset is the maintainer for all 4 projects so might be in the best place to comment.

**Comment by lamont-granquist** [comment]
#1591 #1592
