### ISSUE TITLE
Supermarket: The dependency constraints could not be solved in the time allotted 

### ISSUE THREAD

**Issue by jslusher** [berkshelf/berkshelf#1610]
I have a wrapper cookbook that used to be fine for a `berks update`. Since last week at some point I can't seem to resolve the dependencies in Supermarket in the default time allotted. I've been using `SOLVE_TIMEOUT=1000` to work around the problem, but it takes a very long time and pegs the CPU on the jenkins node on which the updates are run. I've narrowed it down to a particular wrapper cookbook, but I can't tell based on the debug output what dependency might be causing the problem. Here is the output of a failed berks update:

https://gist.github.com/jslusher/3705b9afd3793375f70dac68278fe47f

**Comment by thommay** [comment]
Hi,
which versions of berks/ruby/chefdk etc are you running?
What changed around the time you stopped being able to resolve the dependency set?
If you run with `DEBUG_RESOLVER=1` do you get any further details?

Also, you could try adding
`solver :ruby, :required`
to your berksfile, and seeing if that resolves. You might be just pushing the resolution problems to your chef server at that point, though.

**Comment by jslusher** [comment]
versions:

Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1

**Comment by jslusher** [comment]
After some further investigation, I think it might have something to do with the nginx cookbook and this issue:

https://github.com/miketheman/nginx/issues/412

By eliminating variables, I've found at least that I can run a `berks install` without it timing out if I remove the dependency to nginx in my metadata file. Now when I try and introduce the dependency, I get the following error, which is related to the above issue:

```
    Unable to satisfy the following requirements:

    - `ohai (~> 4.0)` required by `sysctl-0.8.0`
    - `ohai (~> 1.1)` required by `nginx-2.0.0`
```

I think it might also have to do with a circular dependency introduced between two of the wrapper cookbooks. Each of the wrapper cookbooks also have the same nginx dependency. I'm still investigating the nginx problem at the moment. I will update this issue if that does in fact resolve it. Thanks for reaching out!

**Comment by jslusher** [comment]
This ended up being caused by the nginx cookbook and the dependency errors mentioned in that last post. Once I switched over to the (chef_nginx)[https://supermarket.chef.io/cookbooks/chef_nginx] cookbook, the problem went away.

**Comment by legal90** [comment]
I've reproduced the same issue with multiple supermarket sources, but without `nginx` / `chef_nginx` cookbooks participating. Here are the details:

```ruby
## ./metadata.rb

name             'env-chef'
# ...
version          '0.2.2'

depends 'chef-server'
depends 'certificate'
```

```ruby
## ./Berksfile

source 'https://supermarket.chef.io'
source 'https://supermarket.myorg.org'

metadata
```

It fails even with a clean install:
```console
$ rm Berksfile.lock
$ DEBUG_RESOLVER=1 berks install
Resolving cookbook dependencies...
Fetching 'env-chef' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Fetching cookbook index from https://supermarket.prls.net...
The dependency constraints could not be solved in the time allotted.
Unable to find a solution for demands: env-chef (0.2.2)
```
So, only `solver :ruby, :required` helps to solve this. Is that OK to keep this line in Berksfile? Why isn't it set by default?

Versions are:
```
Chef Development Kit Version: 0.18.13
chef-client version: 12.14.57
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.0.0
kitchen version: 1.12.0
```

@thommay Is it reasonable to re-open this issue, or should I file the new one? Thanks.

**Comment by thommay** [comment]
The reason we don't use `solver :ruby` as a default is because the chef server uses libgecode, which is also the default solver in berkshelf; in some cases when using the `:ruby` solver this can mean that you'll get different solutions, and in (fewer) cases you'll get berks to solve but then the chef server won't. (Fewer because the server will generally have a much smaller set of cookbooks to calculate a solution from).

We're loathe to change the solver in chef server since there's so much code out there that might have subtle dependencies on ordering (and all the old versions of berkshelf and librarian that still use gecode.)

This fundamentally isn't an issue with berkshelf, unfortunately, and there's not much we can do to fix it. My strongest suggestion would be to use policyfiles and do all your dependency resolution on the client; after that you'll need to either have a tighter set of dependency rules or use the ruby solver with the knowledge that it might do strange things.
