### ISSUE TITLE
Knife bootsrap windows comes back with error

### ISSUE THREAD

**Issue by airom** [berkshelf/berkshelf#1632]
Hi,

Every time running:
`knife bootstrap windows winrm mynode.mydomain.local -N "myNode" --winrm-user administrator --winrm-password 'SOMEPASSWORD' -r "role[MySwerver]" -j '{ "SomeOptions": { "Option`": "value" }}' -V -y --secret-file THISISMYSECRETKEY`

fails with :
`
ERROR: WinRM::WinRMWSManFault: [WSMAN ERROR CODE: 2147942606]: <f:WSManFault Code='2147942606' Machine='10.165.2.220' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The filename or extension is too long. </f:ProviderFault></f:Message></f:WSManFault>
`
Any idea?

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by airom** [comment]
Thank you @thommay ,
I apologize. I have posted this in the wrong place.(I am not sure how. I intended to report a problem to knife-windows project but somehow probably did not pay attention to which Github window i have open.)
Please delete this if possible.
