### ISSUE TITLE
How to use chef_server source with a different server

### ISSUE THREAD

**Issue by axos88** [berkshelf/berkshelf#1636]
In case of test environments deployed with chef_zero (such as vagrant, kitchen runs, etc), is it possible to use the "real" chef server as a berkshelf source? So that during isolated testing of separate cookbook repositories their dependencies can be pulled from the "live" server?

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
