### ISSUE TITLE
berks vendor should copy metadata.rb also

### ISSUE THREAD

**Issue by ghost** [berkshelf/berkshelf#1651]
Hi, when we launch berks vendor, it's create metadata.json and not copied metadata.rb.  After that we launch kitchen commands like converge and got failures. It's because kitchen launch berks and parse Berksfile which consist metadata method. This method required metadata.rb

Could you please copy metadata.rb also when launch command berks vendor.
Thanks

**Comment by kamaradclimber** [comment]
this is has been implemented in #1652.

**Comment by kamaradclimber** [comment]
Actually change in #1652 broke our workflow (not as in https://xkcd.com/1172/ though).

We put code in our metadata.rb to derive the cookbook version automatically based on git tags.
This assume that the cookbook is always vendored in a context where:
- we have access to the gem that does the version computation (https://github.com/criteo/cookbook-release)
- we have access to git history or to a file `.cookbook_version` that contains the last computed version (as a fallback)

Since #1562, metadata.rb is copied in test-kitchen (and probably on the chef-server). Chef-zero prefers metadata.rb over metadata.json so chef-client fails because it cannot require our gem.

Would it be possible to keep the existing behavior by default and allow users to configure the vendoring of metada.rb (opt-in)?

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/issues/5748
https://github.com/chef/chef-zero/pull/251
https://github.com/chef/chef/pull/5750

and yeah, probably going to have to revert the change and/or make it opt-in before chef-dk ships next week.
