### ISSUE TITLE
Berks conflicting dependencies

### ISSUE THREAD

**Issue by riley69** [berkshelf/berkshelf#1732]
Hi All, I am quite new when it comes to chef and berkshelf. I have created a base cookbook which depend on some other cookbooks. When I run berks install I get this error:

```
Unable to satisfy constraints on package wt_base due to solution constraint (wt_base = 0.3.7). Solution constraints that may result in a constraint on wt_base: [(wt_base = 0.3.7)]
Demand that cannot be met: (wt_base = 0.3.7)
Artifacts for which there are conflicting dependencies: wt_base = 0.3.7 -> [(users ~> 1.8.4), (apt ~> 2.0), (wt_sudo >= 0.0.0), (ssh_authorized_keys ~> 0.3.0), (motd ~> 0.6.4)]Unable to find a solution for demands: apt (2.9.2), chef_handler (3.0.2), motd (0.6.4), ssh_authorized_keys (0.3.0), users (0.3.6), wt_base (0.3.7), wt_mongo (0.1.78), wt_sudo (2.9.5)
```

This my Berksfile:
```
source "https://supermarket.chef.io"

# Mention cookbook names from your repo
%w(users wt_mongo wt_base wt_sudo).each do | cookbook_name |
  cookbook cookbook_name, path: 'cookbooks/' + cookbook_name
end
```
This is my metadata for wt_base cookbook:
```
depends 'users', '~> 1.8.4'
depends 'apt', '~> 2.9.2'
depends 'wt_sudo'
depends 'ssh_authorized_keys', '~> 0.3.0'
depends 'motd', '~> 0.6.4'
```

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
