### ISSUE TITLE
Berks should support generating lock file without downloading/installing cookbooks.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [berkshelf/berkshelf#1737]
I would like to propose a feature request to the berks tool that enables the ability to generate a lock file without actually downloading/installing the cookbook data, similar to the functionality currently in the `bundle lock` command.  Having this functionality would be desirable in environments where a centralized team is responsible for onboarding external artifacts.  The lock file would then be beneficial to provide such a team with a list of the artifacts, as well as the ability to provide an estimation of the number of artifacts that will be required in order to satisfy the primary cookbook and all it's dependencies.

**Comment by lamont-granquist** [comment]
We'd possibly accept a PR to do this, but generally berkshelf doesn't have the same limitations that bundler does -- you don't need to do the equivalent of installing and compiling windows native gems in order to generate a windows-consumed lockfile on a linux/mac system.  It dumps the cookbooks into ~/.berkshelf locally which could maybe be avoided, but that's not really the same kind of blocker to automating around this.
