### ISSUE TITLE
berks upload doesn't handle circular dependencies (v7.0.2)

### ISSUE THREAD

**Issue by grimm26** [berkshelf/berkshelf#1780]
I'm running berkshelf 7.0.2 and `berks upload` goes into and infinite loop of lookup of dependencies when there are cookbooks to be uploaded that depend on each other.

**Comment by lamont-granquist** [comment]
okay here's a sort of a sketch of a repro.

it looks like its sufficient to have two cookbooks on disk via path: specifiers in the Berksfile which both depend on each other and then to try to use them in a third cookbook which you do a `berks install / berks upload` on.  and its necessary to force the `:gecode` solver because the `:ruby` solver does allow circular deps.

**Comment by grimm26** [comment]
@lamont-granquist  on a berks install/update, the ruby solver will error out with: "There is a circular dependency between X and Y".  Neither solver avoids a berks upload that will check dependencies forever.

**Comment by lamont-granquist** [comment]
yeah i found the ruby solver will still solve a direct circular dependency from A->B->A when you're installing or uploading either A or B, but only complains when C is dependent on A or B.  the gecode solver doesn't care about circular deps at all.
