### ISSUE TITLE
chefignore is applied to child cookbooks

### ISSUE THREAD

**Issue by shoekstra** [berkshelf/berkshelf#1817]
Hi,

I'm using Berkshelf 7.0.7 and found a bug where the `chefignore` file in the parent cookbook is applied to depended upon cookbooks.

For example, I have the following directory structure:

```
.
├── ./Berksfile
├── ./chefignore
...
└── ./test
    └── ./test/cookbooks
        └── ./test/cookbooks/testprofiles
            ├── ./test/cookbooks/testprofiles/files
            │   └── ./test/cookbooks/testprofiles/files/default
            │       ├── ./test/cookbooks/testprofiles/files/default/bashrc
            │       ├── ./test/cookbooks/testprofiles/files/default/user1
            │       │   └── ./test/cookbooks/testprofiles/files/default/user1/profile
            │       ├── ./test/cookbooks/testprofiles/files/default/user2
            │       │   └── ./test/cookbooks/testprofiles/files/default/user2/bashrc
            │       ├── ./test/cookbooks/testprofiles/files/default/profile
            │       └── ./test/cookbooks/testprofiles/files/default/user3
            │           ├── ./test/cookbooks/testprofiles/files/default/user3/bashrc
            │           ├── ./test/cookbooks/testprofiles/files/default/user3/profile
            │           ├── ./test/cookbooks/testprofiles/files/default/user3/screenrc
            │           └── ./test/cookbooks/testprofiles/files/default/user3/vimrc
            └── ./test/cookbooks/testprofiles/metadata.rb
```

the `chefignore` contained `*file` and when using Test Kitchen or `berks vendor`, the `profile` files under each user were skipped.

This was confirmed by checking `/tmp/kitchen/cookbooks/testprofiles` in a vagrant VM and checking `cookbooks/testprofiles` after doing `berks vendor`.

Once `*file` was removed from `chefignore` the `profile` files were correctly copied to the vagrant VM and to the vendored cookbooks directory.

Stephen

**Comment by lamont-granquist** [comment]
that does not actually look like a bug to me.  it applies recursively to all directories below it.  it does not know anything about cookbooks themselves such as the metadata.rb or the name inside of it, and it makes no assumptions about directories named `cookbooks`.  

this is actually correct behavior for people who have monorepos and drop a chefignore file a the top of it and expect it to be applied to every cookbook in the repo.

it may have changed behavior in berks 7.0 with the switch from chefignore coming from berks libraries to chefignore coming from chef-client's implementation, but this actually looks more correct, and that looks like a deliberate breaking change in order to have berks behavior match chef/knife/chef-dk behavior.
