### ISSUE TITLE
berks install failing to reslove transative git dependencies 

### ISSUE THREAD

**Issue by jburns24** [berkshelf/berkshelf#1829]
C:\git\test (master) × berks --version
    7.0.8

I have an issue with Berkshelf resolving chained git dependencies. 

I have a test cookbook I generated to narrow down the issue, this cookbook depends on the cookbook `windows-automation` via a git reference. 

### test Berksfile

    # frozen_string_literal: true
    source 'https://supermarket.chef.io'
    
    cookbook 'win-telegraf', path: '../win-telegraf/'
    cookbook 'windows-automation', '~> 0.4.0', git: 'git@git.osky.io:ops/chef-windows-automation.git', branch: 'master'
    # cookbook 'windows-library', '~> 0.1.0', git: 'git@git.osky.io:ops/chef-windows-library.git', branch: 'master'
    
    metadata

### test metadata.rb

    depends 'win-telegraf'
    
    depends 'windows-automation', '~> 0.4.0'
    # depends 'windows-library',  '~> 0.1.0'

`windows-automation` depends on `windows-library` via another git reference

### windows-automation Berksfile

    source 'https://supermarket.chef.io'
    
    metadata
    
    cookbook 'powershell', '~> 6.1.3'
    cookbook 'windows', '~> 4.2.5'
    
    # cookbook 'windows-library', path: '../chef-windows-library'
    cookbook 'windows-library', '~> 0.1.0', git: 'git@git.osky.io:ops/chef-windows-library.git', branch: 'master'

### windows-automation metadata

    supports 'windows'
    
    depends 'powershell', '~> 6.1.3'
    depends 'windows-library', '~> 0.1.0'

 This issue comes when I try to run `berks install` for the test cookbook. I get the following output

    C:\git\test (master) × berks install
    Resolving cookbook dependencies...
    Fetching 'test' from source at .
    Fetching 'win-telegraf' from source at ../win-telegraf
    Fetching 'windows-automation' from git@git.osky.io:ops/chef-windows-automation.git (at master)
    Fetching cookbook index from https://supermarket.chef.io...
    Unable to satisfy constraints on package windows-library, which does not exist, due to solution constraint (test = 0.1.0). Solution constraints that may result in a constraint on windows-library: [(test = 0.1.0) -> (windows-automation = 0.4.0) -> (windows-library >= 0.0.0)], [(windows-automation = 0.4.0) -> (windows-library >= 0.0.0)]
    Missing artifacts: windows-library
    Demand that cannot be met: (test = 0.1.0)
    Unable to find a solution for demands: test (0.1.0), win-telegraf (0.1.0), windows-automation (0.4.0)

This issue gets resolved if in the test cookbook I add a dependency to windows-library. But I am wondering why berkshelf cannot resolve this without the dependency. I feel like I should not need to explicitly depend on all transitive git dependencies.

**Comment by lamont-granquist** [comment]
dup of numerous issues that have been wontfixed, this is the earliest:  https://github.com/berkshelf/berkshelf/issues/690

bundler doesn't do transitive Gemfiles either.

as you can read, there was an attempt to do transitive Berksfiles early on it berkshelf development, but it failed.

if you're doing this a lot you probably need to either:

1.  get a real private supermarket and push development cookbooks up to it, and consume those instead of consuming git sources (this is the industrial-strength approach which preserves the one-cookbook-per-git-repo model)

2.  abandon the one-cookbook-per-repo model and move to a mono repo with all the cookbooks in the same repo and you can just use a path to "../cookbook" and do dev that way (which vastly simplifies depsolving and eliminates this problem, but you will up eventually needing to teach your CI how to kick off only the tests for the cookbooks in the repo which have files which are changing or something like that).
