### ISSUE TITLE
How to use Berkshelf to manage Organization repo like the Librarian-chef does?

### ISSUE THREAD

**Issue by millisami** [berkshelf/berkshelf#535]
I'm a huge fan of Berkshelf and I've released few community cookbooks using it and its awesome.

Now, I'm starting a new chef project and I went ahead with Berkshelf for this too.

But I'm finding some confusions/difficulties using it for the project.

Following is in the Berksfile:

```
site :opscode

cookbook 'mediawiki', github: 'millisami/chef-mediawiki'
cookbook 'sp-mediawiki', path: 'site-cookbooks/sp-mediawiki'
```

I've generated my application cookbook inside the `site-cookbooks` folder.

When I do `berks install`, it errors out:

```
An error occurred while reading the Berksfile: no metadata.rb or metadata.json found at \
/Users/millisami/Code/chef-sp/site-cookbooks/sp-mediawiki
```

Now I'm wondering where do I generate my application `sp-mediawiki` cookbook?

If just create a new one `berks cookbook sp-mediawiki`, it will be similar to the library cookbook.

This sort of flow is perfectly done using `librarian-chef` which I am using on another project.

So, I'm trying to put a line that:
1. Berkshelf is good to develop individual cookbooks
2. Librarian-chef is good to manage the top-level orchestration

Am I right/wrong? How you folks use Berkshelf to manage your Org's chef-repo?

**Comment by seanodell** [comment]
Sorry for resurrecting this ancient thread, but this seems the most relevant place to ask.

I work with an org which does NOT use Berkshelf and has a lot of cookbooks in a single git repo. I want to use Berkshelf to cherry pick the cookbooks out of that repo. I've tried specifying both git: and path: in my Berksfile, but Berkshelf always balks at the repo not having a metadata.rb at the root. I've played around a bit, and I can't figure out how do this short of git cloning the repo down as a separate step and simply using path: to locate the cookbook.

I don't have a lot of say in how that org manages their repo, so rather than take on that battle, I was hoping Berkshelf could make this work. Any ideas?

**Comment by yoshiwaan** [comment]
I'm not sure where else to ask this question either, and considering this seems to be the place of the best discussion around this I guess I'll ask it here.

I'm fully on board with having cookbooks be isolated objects with their own dependencies, using Berkshelf and testing cookbooks in isolation, but the manager baulked here when I suggest having one repo per cookbook, stating his previous experience where managing multiple repos for related code has proved to be a hinderance not an advantage (for general software development, he's zero experience with Chef). He's told me I need to convince him otherwise if I'm do it with one cookbook per repo.

The other way around this that I can see is to simply use directories under the cookbooks repo to do the same thing. So you would have a structure like this:
    -cookbooks_repo
    --company-apache2 (wrapper cookbook)
    ---Berksfile
    --company-php (wrapper cookbook)
    ---Berksfile
    --company-cookbook (role containing cookbook)
    ---Berksfiles
    ---recipes\webserver.rb
    ---metadata.rb (pointing to company-apache2 and company-php)

The Berksfiles for the downstream cookbooks could reference the others by git ref using rel: option for a directory. Each cookbook would also have it's own Vagrantfile for testing.

I guess the problem I'm having is I don't really see the disadvantage of this myself, so can anyone help inform me why I should use one cookbook per repo instead of managing them in directories like this (but still treating them as essentially separate objects otherwise).

**Comment by flatrocks** [comment]
@yoshiwaan, despite all the cheerleading for _one-cookbook-per-repo_, the only undeniable advantage is that Berkshelf and other tools expect it.

I know where your boss is coming from... it is a PITA to deal with a bunch of repos when one would do just fine, especially during development when (despite best efforts) everything's changing a lot.  Consider the extra workflow steps for tracking down and fixing a problem in a cookbook that's a dependency to another of your cookbooks.  What could have been a single commit probably affects three repo's, requiring an exponential(? this may not be a mathematically rigorous statement) amount of git activity.

But my guess is that as time passes, alternate tools will fall behind and you'll spend more and more time trying to make things work under any other architecture.  There's a lot of money and manpower behind the tools for doing this the "official" way, and I think that's the best argument.

**Comment by reset** [comment]
@flatrocks It's not fair for me to come in and say this since I'm the principle author of Berkshelf and I am also the person who pushed this pattern into the spotlight, but just because tools expect it is not the reason this is an advantage. The tools were designed around this pattern for a reason to begin with.

@yoshiwaan @flatrocks cookbooks are software and, as such, should follow the same rules and principles as other software development. Keeping all of your cookbooks in a single repository breaks the [Single Responsibility Principle](http://en.wikipedia.org/wiki/Single_responsibility_principle). It adds noise to the commit history and makes the assumption that all developers should be granted access to all cookbook projects because they would potentially working with one.

A lot of the modern tooling assumes you are coming from a software engineering background or that you are ready for a taste of it. Chef is a big toolbox, however, and you can put things together in anyway that you would like. I personally would recommend sticking to the most travelled path - it works well.

**Comment by yoshiwaan** [comment]
Thanks Jamie. I looked around for your official reasoning behind this and couldn't find it so it's good to hear it from the hors.. developers mouth.

Access control is definitely something I'd not considered. When I sat down and though about it in depth I came up with quite a few other reasons to use one cookbook per repository, most of them fairly pragmatic. The point @flatrocks makes was pretty much at the top of the list.

 * The tools work that way, so it's a path of least resistance once set up
 * There's more help available as more people have implemented this way
 * Your git tags match your cookbook version, plus there's tooling to help with that, e.g. https://github.com/RiotGamesMinions/thor-scmversion, where both your metadata file and build job can reference the version file
 * You can write generic build jobs for all cookbooks as they have the same structure, there's no unique references or paths. Plus if there's a separate org in SCM to house cookbooks you can have your build server do them all without having to manually add anything
 * At some point SCM tags/branches matching cookbook version metadata SemVer numbers might be usable to parse multiple versions of a cookbook. For example in a Berksfile you could point to a github repo for a cookbook and then any tag that matches SemVer could be parsed and understood to be a particular version of a cookbook.

**Comment by reset** [comment]
@yoshiwaan I think you've got a great list there. @flatrocks definitely makes a great point that was worth explaining *why* a lot of tools are built the way that they are.

**Comment by bridiver** [comment]
My big issue with the one repo per cookbook is the sheer number of repositories that you now have to manage. It seems like a lot of added complexity and after reading through I'm not seeing anything that couldn't be done just as easily with a single repo. If we keep them separate, now we have to setup CI, phabricator, etc.. for every single one of them individually. We've looked at similar things in the past like keeping application code in one repo vs multiple repos with gems and development and debugging quickly become a nightmare. Of course there are big advantages to being able to pull in git-based cookbooks, but within an organization splitting them out just seems to complicate development. If you need one somewhere else you can easily extract it, but why do that proactively if it may never be necessary?

**Comment by bridiver** [comment]
I also don't agree with "Keeping all of your cookbooks in a single repository breaks the Single Responsibility Principle". We don't keep each class or even module of our application code in it's own repo, so why is it a problem here? I think applying the single responsibility principle to a repository is really stretching its meaning.

**Comment by sethvargo** [comment]
Hi @bridiver 

I would recommend taking your thoughts to the Chef mailing list or open a [Chef RFC](https://github.com/chef/chef-rfc) if you disagree with this approach. Thanks!

**Comment by reset** [comment]
@bridiver you don't keep a class or module in it's own repository because it is a component of a project. Project's, like a cookbook, are an umbrella for those components. Best practices in version control systems suggest that you version control things at the project level.

You can organize your projects however you'd like, you absolutely don't need to follow any documented best practices. Sometimes by going off the well travelled road you'll land on something which becomes a best practice.

Three years ago that's what the Berkshelf project did. It won't ever support the single repository pattern as a first class citizen because the tool and it's maintainers don't believe that is a best practice. You can absolutely use the tool to manage your cookbooks however you'd like, though!

If I'd recommend reading through [The Pragmatic Programmer](http://www.amazon.com/The-Pragmatic-Programmer-Journeyman-Master/dp/020161622X) which was a big influence for me and helped direct the development of this, and all of the other open source tools I've created or been a part of.

**Comment by bridiver** [comment]
But that's my point. We have a bunch of cookbooks and they are all part of a coherent project and I think that's the case more often than not. It feels like this is taking a pattern that might be necessary for a very large organization with lots of different unrelated projects sharing cookbooks and access control issues and pushing it on everyone. Of course everyone is free to do their own thing, but I think this pattern should be considered in the context of your organization and not held up as the "best solution"

**Comment by reset** [comment]
@bridiver it may _appear_ that they are all part of the same project, but they aren't. You have one cookbook which is part of that software project and then you have dependencies of that. The dependencies, like any other software library, can be consumed by other projects.

If you are coming at this from a systems administration perspective then it is very easy to see a mass of cookbooks as being "one project". They just aren't.

**Comment by bridiver** [comment]
@reset that is simply one way to think about it and it's not realistic to say that you have the one right view that applies in every case. I am not coming at this from a systems administration perspective, I am coming at this with substantial experience as a software developer. It's fine for software to be opinionated, but IMO good tools allow you to swap out those opinions.

**Comment by reset** [comment]
@bridiver I think it's important to address the idea that "this is hard" or "we should grow into this slowly" before we move anywhere else with this discussion. I'm not part of a large organization by any means - we have 12 engineers. Versioning software with dependencies that include projects created internally to an organization is something that software engineers are very used to in 2015.

**Comment by reset** [comment]
@bridiver like I had said before, you are of course free to follow whatever you believe is the right path for your organization. You can absolutely use Berkshelf to manage a single repository - there are a number of blog posts and guides that you can follow on how people are doing this. We just aren't doing you any favors to make it a first class citizen.

**Comment by bridiver** [comment]
@reset I'm not saying "grow into this slowly", I'm saying that it's added complexity that is unnecessary in a lot of cases. Like anything else it has it's advantages and disadvantages and not everyone wants to make the same tradeoffs

**Comment by yoshiwaan** [comment]
As someone who went through this whole process and had to make decisions about how to implement without fully understanding everything I think I'm in a decent position to comment on this.

I ended up following the best practices recommended here, namely having a single repository per cookbook, and I'm finally seeing the full value of making those decisions. There is definitely an extra outlay of work initially but now that's in the past I just don't see how I could have ended up in such a good position.

The advantages for me are:
 * Development is easy
 * Integration with a build server is easy
 * I have tags to match cookbook versions
 * Everything gets tested in right place

Didn't see full benefit until I moved to using a build job for cookbooks. Because each cookbook is a single repo it means I can use the same build script for all of my cookbooks, with the only variable being the repository to build. The same test suite (foodcritic -> chefspec -> server spec) get run every time for every cookbook. I also get to tag my repository with the current cookbook build version as a part of the build, so I have an easy reference in github for my versions.

When I want to deploy a new version of a cookbook I make my changes, push to a certain branch and my build server automatically does it's thing and I can go and do something else. If I want to get more clever in the future I could have my environment cookbook trigger a build (which is a slightly different job) from a successful upstream cookbook build and have that available with a new version too, I have the option. Right now I do that manually when I need and all the new changes applied by other cookbook builds get tested in one go when the tests for that cookbook run.

Technically this is 'added complexity' because behind the scenes there's plenty going on, and it was a good investment of time to set up, but in terms of ease of using it's never been easier for me or anyone else here to develop a cookbook. Everything works in such a simple way from the developers perspective and I don't see how that could have been possible having a bunch of cookbook directories in my repository. That being said a single repo can definitely work and it's something I seriously considered, you can put up artificial walls so each cookbook is maintained individually, but it just seems sub optimal in the long run as you're essentially trying to do the same thing you can do with a single repo per cookbook, but less successfully.

The most difficult part of the whole process, at least when you're new, is understanding why you're doing what you're doing in the first place as it takes such a long time and an intermediate understanding of all the components to see any benefit.

**Comment by bridiver** [comment]
That's interesting because development is one part I really worry about getting complicated. Sometimes you have to iterate over cookbooks to sort out issues with your application tests due to breaking changes with upgrades, configuration, etc... and there can be a lot of changes to sort out the issue. That's fairly simple when you don't have to commit things to test them, but it can get tedious when you have to commit, tag, update dependencies, etc... because your cookbook tests won't catch things you didn't know you needed to test. I have seen plenty of examples of workflow with Berkshelf for developing a cookbook, but it *seems* like the workflow for dealing with unexpected issues when running application tests again VMs configured with these cookbooks would be cumbersome. Is there a workflow that doesn't involve repeated commits to the remote repo or making manual changes and then sorting back through them to update the cookbook?

**Comment by yoshiwaan** [comment]
I'm not entirely sure I get what you're asking...
I use test kitchen to iterate on a test instance of the same type as where the cookbook will be deployed to, running kitchen on my local machine when developing. Running `kitchen converge` will apply the current cookbook to the node and berkshelf will pull in dependencies as needed if the cookbook has a Berksfile. If you use the chef_zero provisioner then you can replicate a chef-client run and if you use a cloud service then there are test kitchen plug ins to run spool instances there.

I only push something to build when I've sorted out the kinks.

Maybe when I say developing is easy I should say the whole flow of development to deploy is easy.

**Comment by bridiver** [comment]
An example from the past was upgrading from Postgres 8.x to 9.x. There were breaking changes in how Postgres handled timezones and we didn't discover them until we ran the app tests against the updated cookbook. Figuring out what needed to change took some back and forth with changes to both the app code and the cookbook. Since we had everything in a single repo for chef, the whole workflow only involved local changes to the chef repo and the app repo and wasn't pushed out to either until everything worked.

**Comment by sethvargo** [comment]
@bridiver you might find this post interesting: https://sethvargo.com/berkshelf-workflow/, it details the workflow @yoshiwaan is discussing a bit more. I think it would suit your upgrade of postgres just fine.

**Comment by glenjamin** [comment]
Sorry for dredging this ol' chestnut up again, I'm building up a new project and facing the how-many-chef-repos question - and this thread seems to be a font of knowledge on that front.

My context is a relatively small "ops" team ~5 people, with a medium size dev team (~40), building, deploying and running a co-ordinated suite of applications.

Things I'm sold on:
* Having library cookbooks be in their own repo (ideally on github, or githubbable)
* Having application cookbooks be in their own repo (ideally on github, or githubbable)
* Having an "infrastructure repository" which contains data_bags, roles, and environment files

The bit I'm strugging with is how and where wrapper & environment cookbooks fit into this. At the moment I've taken the path of least resistance, and included some cookbooks in the infrastructure repository along with Berksfile to pull in library and application cookbooks from supermarket.

The cookbooks in the main repo are mostly about doing things specific to our organisation and tying those together into a whole ecosystem. This is the bit where I'm struggling to see how to represent this across many independently versioned cookbooks.

When producing a bunch of independent but related software applications, the master chef repo has always been the piece I've used to stitch them all together.

Can anyone point me in the direction of some good examples of this done well?

**Comment by tknerr** [comment]
@glenjamin my personal preference is to stitch the individual pieces of one application / server together in a "top-level cookbook" (terminology varies, it's probably the same as a "role cookbook").

This means in my infrastructure repository I can now use different versions of it:
https://github.com/tknerr/sample-infrastructure-repo/blob/master/Vagrantfile#L30-L31
https://github.com/tknerr/sample-infrastructure-repo/blob/master/Vagrantfile#L51-L52

Works for me but YMMV... ;-)

**Comment by glenjamin** [comment]
@tknerr Thanks! that's a helpful example.

The part I'm still strugging to get my head around is when an application sub-components are spread across many different nodes. My general preference would be to try and use searches for the bits of my app to find each other - is this still a recommended way?

Common examples which spring to mind: collectd deamons finding their server, application servers finding the database cluster, jenkins finding it's slaves. A load balancer having a bunch of otherwise unrelated microservices attached as independent vhosts.

**Comment by patcon** [comment]
Here's and issue related to something librarian-chef could handle, but Berkshelf can't atm, in case anyone here has any thoughts:

[Allow using a test cookbook from a subpath of another cookbook](https://github.com/berkshelf/berkshelf/issues/1505)

**Comment by Mister-Meeseeks** [comment]
Sorry to bump this thread. But Google seems to have deemed it the de facto discussion forum for Berksfile best practices. I'm not sure if I'm either missing some functionality in Berkshelf or am not grok'ing the underlying philosophy. (Don't have much Ruby(gem) experience, so that probably doesn't help). But let's say we have three cookbooks {X, Y, Z}. X depends on Y. Y depends on Z. X has only a transitive dependency on Z. However in cookbook Z's Berksfile looks like this:

`cookbook 'Y', path: /cookbooks/Y/`
`cookbook 'X', path: /cookbooks/X/`

If the reference to X is left out, Berkshelf will raise a "missing artifact" fatality. Nearly every major package manager recursively evaluates dependency. Otherwise it's a major violation of the DRY-principle. What if the path to cookbook X changes? What if cookbook Y is modified and requires another dependency? Or we want to freeze Y's version of X? It requires editing not just Y's Berksfile, but also Z's. What if hundred of cookbooks are dependent on Y. Should we really have to edit 100+ Berksfiles just to modify one library cookbook?

I don't think DRY is an absolutely inviolable principle. But not evaluating transitive dependencies seems like a pretty limiting handicap for a package manager. One that doesn't seem accompanied by any substantial upsides outside a few corner cases. But I feel like I have to missing something obvious, right?
