### ISSUE TITLE
berks install with --berksfile option does not work

### ISSUE THREAD

**Issue by tknerr** [berkshelf/berkshelf#594]
Steps to reproduce:
1. Clone a repo with a Berksfile in it

```
D:\tmp>git clone https://github.com/opscode-cookbooks/bluepill.git
Cloning into 'bluepill'...
remote: Counting objects: 492, done.
remote: Compressing objects: 100% (203/203), done.
ta Re189ce), ivreingus oed bj46ec5 (tsdel: ta 9 10%66 (4)  /4
Receiving objects: 100% (492/492), 61.64 KiB, done.
Resolving deltas: 100% (189/189), done.
```
1. Do _not_ `cd` into that directory, but try to run `berks install` from here:

```
D:\tmp>berks install --berksfile bluepill\Berksfile
An error occurred while reading the Berksfile: no metadata.rb or metadata.json found at D:/tmp/bluepill/bluepill
```

The `metadata.rb` actually exists, but it seems the path got messed up `D:/tmp/bluepill/bluepill`.

Environment:
- Win7 64-Bit
- Berkshelf 2.0.0.beta (rubygems) and 2.0.0.beta (current master)

**Comment by vinodhalaharvi** [comment]
I landed here because  I have a use case for uploading the cookbooks in parallel. Looks like I am running into a race condition  as the berks upload seem to generate "metadata.json" file and having two cookbooks dependent on the same common cookbook, seem to not fit the parallel cookbook upload scenario.  For example I have cookbook B and C depend on cookbook A. Now how do I upload B and C in parallel?  Currently I am running B and C in parallel threads, but that fails due to the error that metadata.json file  is not found. Any help is much appreciated.
